language: python

python:
    - 3.2
    - 2.7
    - 2.6

env:
    - NUMPY_VERSION=1.6.2
    - NUMPY_VERSION=1.5.1

before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy cython

install:
   - pip install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
   - pip install --upgrade Cython --use-mirrors
   - pip install --upgrade nose --use-mirrors

script:
   - make all
   - make bench
