os: linux
language: generic
cache:
    directories:
      - $HOME/.cache/pip
      - .hypothesis

git:
    depth: false

jobs:
    fast_finish: true
    include:
        - os: linux
          arch: arm64
          env: TEST_DEPS="numpy"
               PYTHON_VERSION="3.7"
               PYTHON_ARCH="64"

        - os: linux
          arch: ppc64le
          env: TEST_DEPS="numpy gfortran_linux-ppc64le=8.2.0"
               PYTHON_VERSION="3.7"
               PYTHON_ARCH="64"

before_install:
    - uname -a
    - source "tools/travis/conda_setup.sh"

install:
    - source "tools/travis/conda_install.sh"

script:
    - ./tools/travis/bn_setup.sh

notifications:
    email:
        on_success: never
        on_failure: always
